### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by JuanjoA** [sonicd300/TNF-IonicUtils#1]
Hi, I test the signature tool, but, I have a error when run:

Error: Can't find variable: SignaturePad
openSignatureModal@http://localhost:8100/components/signature_pad/signaturePad.directive.js:28:49
$parseFunctionCall@http://localhost:8100/lib/ionic/js/ionic.bundle.js:20270:23
http://localhost:8100/lib/ionic/js/ionic.bundle.js:52468:21
$eval@http://localhost:8100/lib/ionic/js/ionic.bundle.js:22326:28
$apply@http://localhost:8100/lib/ionic/js/ionic.bundle.js:22425:28
http://localhost:8100/lib/ionic/js/ionic.bundle.js:52467:19
eventHandler@http://localhost:8100/lib/ionic/js/ionic.bundle.js:10939:25
dispatchEvent@[native code]
triggerMouseEvent@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2856:20
tapClick@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2845:20
tapMouseUp@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2915:13

My index.html:
 
    <script src="js/app.js"></script>
    <script src="js/controllers.js"></script>
    <script src="js/services.js"></script>
    <script src="components/signature_pad/signaturePad.directive.js"></script>

I use demo app tabs, and on dashboard (tab.dash.html) insert:

Entrar Firma:
    <tnf-signature-pad ng-model="firma"></tnf-signature-pad>

    Resultado:
    <img ng-src="{{firma}}" />

Thx!
Juanjo

PS: Ok, need the library:
    <script src="js/signature_pad.js"></script>

Now work ok.
Thx

**Comment by sonicd300** [comment]
Did it work?

Im considering to move this directive to it's own repo because it has a dependency on: https://github.com/szimek/signature_pad
I want to add bower sugar too.

Let me know if you need any help
Cheers
